### PR TITLE
fix #408, handle Ctrl+C(sigint) gracefully.

### LINKED ISSUE #408: ActorSystem should handle Ctrl+C (SIGINT) gracefully
On Linux, I found the SIGINT will be passed from parent process to child process, and will shutdown the child process directly. When this happen, ActorSystem don't get the chance to cleanup itself, like closing the connection, closing the file handler.

### PR DESCRIPTION
**Pull request by clockfly**
[Review on Reviewable](https://reviewable.io/reviews/intel-hadoop/gearpump/409)

### CODE REVIEW

**Comment by manuzhang** [comment]
hi, in which case will a user hit `Ctrl+C` to interrupt an `ActorSystemBooter` ?

**Comment by clockfly** [comment]
For example, when user starts a worker, and then he may ctrl+C to stop the worker.

**Comment by clockfly** [comment]
In this case, all child processes of worker will receive a Ctrl+C on linux. Please check #408, there are description about how Ctrl+c can be propagated to child processes.

**Comment by manuzhang** [comment]
+1

**Pull request merged**
