### PR TITLE
fix #217 Add Distributed Shell

### LINKED ISSUE #217: Write a small custom AppMaster example, which can run distributed shell.
Requirements:

1. An appMaster, which accept commands and response with comand line outputs dynamically.

### PR DESCRIPTION
**Pull request by huafengw**
[Review on Reviewable](https://reviewable.io/reviews/intel-hadoop/gearpump/256)

### CODE REVIEW

**Comment by manuzhang** [comment]
this pr seems to combine two features, could you break it down ?

**Comment by huafengw** [comment]
Most of code is under experiments and the changed part in core is also needed.

**Comment by whjiang** [comment]
Hi Huafeng, please make two following changes:
1. add distributedshell folder under experimental and move corresponding code there.
2. add a README.md file to list the purpose of this work and examples.

**Comment by clockfly** [comment]
Good work, please rebase on #255

**Comment by clockfly** [comment]
After that, make sure unit test is added.

**Comment by clockfly** [comment]
+1

**Comment by huafengw** [comment]
temporarily close this PR due to the API change

**Pull request closed without merging**
