### PR TITLE
fix#679 add a InterMediateService to forward rest request

### PR DESCRIPTION
**Pull request by huafengw**
Seems spray do not support forward a rest request

### CODE REVIEW

**Comment by huafengw** [comment]
Now the rest api looks like 
``http://localhost:8090/api/v1.0/internal/intermediate/delete/api/v1.0/appmaster/0```
and the intermediate rest only support DELETE and PUT

**Comment by clockfly** [comment]
1. Maybe we should not duplicate the version twice. 
2. This URL should only be available for POST, as GET can be cached by intermediate proxy.

**Comment by huafengw** [comment]
Updated. Now the rest api looks like
``http://localhost:8090/api/v1.0/internal/intermediate/delete/appmaster/0``
and this url only support POST

**Comment by clockfly** [comment]
+1

**Pull request merged**
