### PR TITLE
Fixes #27 Integrate YARN into scheduler

### PR DESCRIPTION
**Pull request by kkasravi**
[Review on Reviewable](https://reviewable.io/reviews/intel-hadoop/gearpump/645)

### CODE REVIEW

**Comment by kkasravi** [comment]
created a new branch that just holds changes made on the yarn branch. Both yarn_1 and yarn will be deleted once we merge to master.

**Comment by clockfly** [comment]
@kkasravi 

I didn't see the config related code. As you know, the master config and worker config need to be different.

Have you configed and provisioned them correctly?

**Comment by kkasravi** [comment]
Check worker now - ./core/src/main/scala/org/apache/gearpump/cluster/main/Worker.scala

**Comment by kkasravi** [comment]
MainSpec is failing due to Worker not registering which is also what Tomek is seeing - checking...

**Comment by kkasravi** [comment]
target/pack/bin/worker was resulting in a NPE which is fixed.
Now you can run 'target/pack/bin/worker' or target/pack/bin/worker -master <host>:port,<host>:port'

I am seeing this test failure:
[error] (gearpump-streaming/test:test) sbt.TestsFailedException: Tests unsuccessful

Checking on why ...

**Comment by kkasravi** [comment]
@TomaszT @clockfly 
This will now easily merge to main and is based on Tomek's branch issue_27_vol2 with a fix for starting worker which may fix the problem Tomek was seeing earlier on CDH.

**Comment by clockfly** [comment]
+1

**Comment by kkasravi** [comment]
@Sean @TomaszT 
Once Tomek validates yarn_1 is equivalent to his branch 'issue_27_vol2' (plus the worker fix) we can delete the yarn branch from master. Hopefully we can merge yarn_1 -> master in the next 24 hours or so.
I will start testing pipeline later today.

**Comment by clockfly** [comment]
Hi Kam,

Please take some sleep.

Take care!!!

**Comment by kkasravi** [comment]
Thanks Sean :)

**Comment by huafengw** [comment]
+1

**Comment by clockfly** [comment]
I will do the merge now.

if there are problems, let's fix it in further PR.

**Pull request merged**
