### PR TITLE
Fixes  #400 Kafka -> HBase pipeline

### LINKED ISSUE #400: Kafka -> HBase pipeline
We would like to see a use case where the source is kafka and a sliding window within the DAG calculates and updates an average and then writes this to hbase. 
Subtasks:
- [ ] #685 Pipeline: Fix runtime classpath and fat jar assembly to take advantage of jars on target node
- [ ] #686 Pipeline: Define all schema data using upickle
- [ ] #687 Pipeline: Create HBase tables, columns or assume they are precreated and return appropriate error info to AppMaster
- [ ] #688 Pipeline: Dynamically set zookeeper, kafka and hbase server locations in respective taskactor's prestart's
- [ ] #689 Pipeline: Possibly add CLI options to pipeline for topic, tables which would override pipeline.conf
- [ ] #690 Pipeline: Define DAG streaming behavior
- [ ] #714 Pipeline: extend KafkaConfig -> PipelineConfig
- [ ] #724 Pipeline: add data generator to pipeline example

### PR DESCRIPTION
**Pull request by kkasravi**
Still TODO  #714 

Note "org.slf4j" % "jcl-over-slf4j" % slf4jVersion was removed due to conflicts with commons_logging during assembly.

[Review on Reviewable](https://reviewable.io/reviews/intel-hadoop/gearpump/717)

### CODE REVIEW

**Comment by clockfly** [comment]
Hi Kam,

Can you add some UT for new added class.

**Comment by clockfly** [comment]
And seems there is build error, can you check it?

**Comment by clockfly** [comment]
```
Note "org.slf4j" % "jcl-over-slf4j" % slf4jVersion was removed due to conflicts with commons_logging during assembly.
```
What is the conflict?

**Comment by kkasravi** [comment]
Build error fixed. 
jcl-over-slf4j fixed by adding "provided" - this may not be the right way to do it.
Adding some UT. Will resubmit when done.

**Pull request closed without merging**
