### PR TITLE
issue #27 - setting up commands for the master, worker(s) and services (...

### PR DESCRIPTION
**Pull request by kkasravi**
...REST server).

Commands we need to invoke :
$JAVA_HOME/bin/java org.apache.gearpump.cluster.main.Master -ip <hostip> -port <port>
$JAVA_HOME/bin/java org.apache.gearpump.cluster.main.Worker -master <host>:<port>
$JAVA_HOME/bin/java org.apache.gearpump.cluster.main.Services -master <host>:<port>

[Review on Reviewable](https://reviewable.io/reviews/intel-hadoop/gearpump/628)

### CODE REVIEW

**Comment by clockfly** [comment]
Hi Kam,

@TomaszT  have another patch, can you check with him to see whether these two patch conflict with each other?

**Comment by kkasravi** [comment]
Hi Sean - thanks for asking. I'm working from his branch so it should be ok. I made some very minor changes.

**Comment by kkasravi** [comment]
Hi Sean - let me know if you would like to merge or i can. For subbranches under master - it is ok not to have +1 from more than one team member?

**Comment by clockfly** [comment]
+1

**Comment by clockfly** [comment]
Tomek said he will have a new PR today. 

I am not sure he is openning a new branch or still using the branch you mentioned.

**Comment by clockfly** [comment]
I think we should stick to the review process no matter it is a branch or on trunk.

The reason is that, when we do back-merge from a feature branch to trunk, it is typically difficulty to check all the changes.

**Comment by kkasravi** [comment]
yes ok - it is then a good idea to have someone +1. Since you gave +1 on this I will merge now. Tomek will have another PR later today.

**Pull request merged**
