### PR TITLE
moved dashboard code from conf to service/dashboard

### PR DESCRIPTION
**Pull request by stanleyxu2005**
[Review on Reviewable](https://reviewable.io/reviews/intel-hadoop/gearpump/440)

### CODE REVIEW

**Comment by clockfly** [comment]
There is an error, can you check it?
```
[0m[[33mwarn[0m] [0m	::::::::::::::::::::::::::::::::::::::::::::::[0m
[0m[[33mwarn[0m] [0m	::          UNRESOLVED DEPENDENCIES         ::[0m
[0m[[33mwarn[0m] [0m	::::::::::::::::::::::::::::::::::::::::::::::[0m
[0m[[33mwarn[0m] [0m	:: io.spray#spray-can_2.11;1.3.2-20140909: not found[0m
[0m[[33mwarn[0m] [0m	:: io.spray#spray-routing_2.11;1.3.2-20140909: not found[0m
[0m[[33mwarn[0m] [0m	::::::::::::::::::::::::::::::::::::::::::::::[0m
[0m[[0minfo[0m] [0mResolving org.scala-lang#scala-library;2.11.5 ...[0m
```

The build log is here: https://api.travis-ci.org/jobs/50321798/log.txt?deansi=true

**Comment by clockfly** [comment]
The build fail is caused by new added dependency 
"com.wandoulabs.akka" %% "spray-websocket" % sprayWebSocketsVersion, 

It rely on version pray-can_2.11;1.3.2-20140909
but we have pray-can_2.11;1.3.2

check the commit:
https://github.com/intel-hadoop/gearpump/commit/98bdf97d6d8f6ec9eeb436c5f66b4797c50f2a64#diff-215113124f1de02f228327ba7abb45f7

**Comment by clockfly** [comment]
However, it is not caused by this PR. 

I will merge this for now. Stanley, please open an issue for Kam about the build error we found.

**Comment by kkasravi** [comment]
I'll fix sometime today, thanks

**Pull request merged**
