### PR TITLE
fix #890: add cloudera manager integration support for gearpump

### LINKED ISSUE #890: add cloudera manager integration support
support distribute gearpump package and start/stop gearpump services via Cloudera Manager.

### PR DESCRIPTION
**Pull request by whjiang**
Add cloudera manager integration support.

Currenlty, general parameter setting is not working (but auto set master address based on role selection working).

### CODE REVIEW

**Comment by whjiang** [comment]
Not understand why HistoryMetricsServiceSpec will fail:

```
[info] HistoryMetricsServiceSpec:
[info] SingleValueMetricsStore
[info] - should retain metrics and expire old value *** FAILED ***
[info]   5 did not equal 3 (HistoryMetricsServiceSpec.scala:68)
[info] MinMaxMetricsStore
[info] - should retain min and max metrics data and expire old value
[info] HistogramMetricsStore
[info] - should retain corse-grain history and fine-grain recent data
[info] MeterMetricsStore
[info] - should retain corse-grain history and fine-grain recent data
[info] CounterMetricsStore
[info] - should retain corse-grain history and fine-grain recent data
[info] HistoryMetricsService
[info] - should retain lastest metrics data and allow user to query metrics by path
```

**Comment by whjiang** [comment]
The UT failure is not relevant to this PR. It has been addressed by another PR #894.

**Comment by clockfly** [comment]
@whjiang 

Would you want to host this as a standalone project at github.com/gearpump?

**Comment by clockfly** [comment]
Close this as we will do this in repo https://github.com/gearpump

**Pull request closed without merging**
