### PR TITLE
fix #910 change package name from org.apache.gearpump to gearpump

### LINKED ISSUE #910: replace package name from "org.apache.gearpump" to "gearpump"

### PR DESCRIPTION
**Pull request by huafengw**
[Review on Reviewable](https://reviewable.io/reviews/intel-hadoop/gearpump/912)

### CODE REVIEW

**Comment by clockfly** [comment]
Hi Huafeng,

This is a requirement from Apache Foundation before incubation. 

We need to make sure we have retained all the history when this rename. Please double check this and do some experiments to see whether the history is still there.

**Comment by huafengw** [comment]
ok, I'll do that.

**Comment by clockfly** [comment]
how is this going?

**Comment by huafengw** [comment]
Waiting for other big pull request to be merged into master.

**Comment by manuzhang** [comment]
flink has done this before when they rename from stratosphere https://github.com/apache/flink/commits/master?page=70

**Comment by stanleyxu2005** [comment]
Will the new namespace to be "io.gearpump" or "gearpump"? I vote for "io.gearpump"

**Comment by clockfly** [comment]
+1 for io.gearpump

**Comment by clockfly** [comment]
Lets wait for PR
1. Connector framework.
2. Dynamic DAG.
3. Additions? 

After these, we will restart this process.

**Comment by manuzhang** [comment]
The connector framework including refactoring external modules would require more time and we already have the interface in so I suggest we restart this right after Dynamic DAG.

**Comment by manuzhang** [comment]
shall we restart this since those two PRs are in ?

**Comment by huafengw** [comment]
Agree, I'll do that when kafka_hdfs is merged.

**Comment by huafengw** [comment]
Close this pull request, will submit another one since the code has been refactored a lot.

**Comment by kkasravi** [comment]
we have scalajs to merge which has dependencies on backend due to shared messages.

**Pull request closed without merging**
