### PR TITLE
fix #1099: added api /userapp/submit to submit userapp to master

### LINKED ISSUE #1099: Submit user application via restapi
Allow user to upload an application (JAR) and submit it to master. The file will be removed after the submission is done/failed. Response is expected to be `{"status":0}`. In case of error, the response will be `{"status":1}`.

### PR DESCRIPTION
**Pull request by stanleyxu2005**

### CODE REVIEW

**Comment by clockfly** [comment]
@stanleyxu2005 

Can you make a PR to branch https://github.com/intel-hadoop/gearpump/tree/kafka_hdfs instead?

**Comment by kkasravi** [comment]
There may be an error in the test spec

[info] SubmitUserApplicationServiceSpec
[info] - should submit an invalid jar and get status != 0 *** FAILED ***
[info]   "[There was an internal server error.]" did not equal "[{"status":1}]" (SubmitUserApplicationServiceSpec.scala:48)

**Comment by stanleyxu2005** [comment]
I'll investigate it and also including the ui part change.

**Comment by stanleyxu2005** [comment]
@kkasravi The unittest failure has been corrected. Now the PR (including ui changes) is ready for review.

**Comment by clockfly** [comment]
+1

**Pull request merged**
