### PR TITLE
Fixes #308. List and related $colon$colon were added to reference.conf. ...

### LINKED ISSUE #308: Add a complex DAG example
This example will allow experimenting with various input formats and code generation.

### PR DESCRIPTION
**Pull request by kkasravi**
...Will update wiki when merged.

[Review on Reviewable](https://reviewable.io/reviews/intel-hadoop/gearpump/329)

### CODE REVIEW

**Comment by kkasravi** [comment]
Looks like timing related issues for SplitSpec, NodeSpec

**Comment by kkasravi** [comment]
complexdag passes locally on my machine
$ sbt
> project gearpump-examples-complexdag
> test

sbt test does have a number of failures like org.apache.gearpump.cluster.main.MainSpec also timeout related.

**Comment by clockfly** [comment]
+1

Please rebase on master to check the build failure after #327

**Comment by kkasravi** [comment]
Thanks. I'll rebase once #327 is merged.

**Pull request merged**
