### PR TITLE
fix #396, bump up kafka version to 0.8.2.0

### LINKED ISSUE #396: bump up kafka version to 0.8.2.0
Kafka has just [released 0.8.2.0](https://archive.apache.org/dist/kafka/0.8.2.0/RELEASE_NOTES.html).

major features, improvements, fixes,

 - A new Java producer for ease of implementation and enhanced performance.
 - A Kafka-based offset storage.
 - Delete topic support.
 - Per topic configuration of preference for consistency over availability.
 - Scala 2.11 support and dropping support for Scala 2.8.
 - LZ4 Compression.

### PR DESCRIPTION
**Pull request by manuzhang**
[Review on Reviewable](https://reviewable.io/reviews/intel-hadoop/gearpump/401)

### CODE REVIEW

**Comment by clockfly** [comment]
build fail?

**Comment by manuzhang** [comment]
this seems to do with Scala version as Kafka depends on 2.11.5. Is it ok to bump up scala version to 2.11.5 ?

**Comment by clockfly** [comment]
It is OK.

**Comment by clockfly** [comment]
2.11.5 and 2.11.4 are compatible.

**Comment by clockfly** [comment]
+1

**Pull request merged**
