### PR TITLE
fix #422, fix worker address bug

### LINKED ISSUE #422: [Dashboard] create a UI for master informations
Master task is #11 

The UI should contains information about workers and applications.

The worker information includes:

“id”: string, 
   “state”: string, 
Host:
Port:
Alive for:
Log path:
config
   executors:
       executor1: 
appId, 
executorId
slots taken
       executor2: 
appId, 
executorId
slots taken

   available slots:
   “resources”: [
        {“total slots”:  int}, //…
   ]

and system load information. (like disk space, memory, CPU, load)

The application information includes:

“name”: string,
   “appmaster”: string,
appId: Int
status: running or dead.
submission date:    
“application url”  //for redirect
Username:
Executors:
   Executor1:
       Worker1
AppMaster address: 
    Worker xx

### PR DESCRIPTION
**Pull request by manuzhang**
[Review on Reviewable](https://reviewable.io/reviews/intel-hadoop/gearpump/451)

### CODE REVIEW

**Comment by clockfly** [comment]
Can you explain about this change? 

```
+      val host = address.host.getOrElse("")
+      val port = address.port.getOrElse(-1)
```

**Comment by clockfly** [comment]
Why address.host.get will fail in the first place?

**Comment by manuzhang** [comment]
because the address of work in the following spec of `WorkerSpec` is `akka://WorkerSystem`.

```scala
  "Worker" should {
    "init its resource from the gearpump config" in {
      val workerSystem = ActorSystem("WorkerSystem", ConfigFactory.parseString(s"${Constants.GEARPUMP_WORKER_SLOTS} = $workerSlots"))
      val worker = workerSystem.actorOf(Props(classOf[Worker], mockMaster.ref))
      mockMaster watch worker
      mockMaster.expectMsg(RegisterNewWorker)

      worker.tell(WorkerRegistered(workerId), mockMaster.ref)
      mockMaster.expectMsg(ResourceUpdate(worker, workerId, Resource(workerSlots)))

      worker.tell(UpdateResourceFailed("Test resource update failed", new Exception()), mockMaster.ref)
      mockMaster.expectTerminated(worker, 5 seconds)
      workerSystem.shutdown()
    }
  }
```

**Comment by clockfly** [comment]
The fix is included in 
https://github.com/intel-hadoop/gearpump/pull/455

**Comment by clockfly** [comment]
Close this as this is included by #455

**Pull request closed without merging**
