### PR TITLE
Issue #958

### PR DESCRIPTION
**Pull request by kkasravi**

### CODE REVIEW

**Comment by manuzhang** [comment]
a few tests failed 

```
[error] (gearpump-examples-complexdag/test:test) sbt.TestsFailedException: Tests unsuccessful
[error] (gearpump-examples-transport/test:test) sbt.TestsFailedException: Tests unsuccessful
[error] (gearpump-examples-fsio/test:test) sbt.TestsFailedException: Tests unsuccessful
[error] (gearpump-examples-sol/test:test) sbt.TestsFailedException: Tests unsuccessful
```

it seems all of them are timeout like

```
[info] DagSpec:
[info] - Dag should succeed to submit application with required arguments *** FAILED ***
[info]   java.lang.AssertionError: assertion failed: timeout (25 seconds) during expectMsgClass waiting for class org.apache.gearpump.cluster.ClientToMaster$SubmitApplication
[info]   at scala.Predef$.assert(Predef.scala:165)
[info]   at akka.testkit.TestKitBase$class.expectMsgClass_internal(TestKit.scala:423)
[info]   at akka.testkit.TestKitBase$class.expectMsgType(TestKit.scala:405)
[info]   at akka.testkit.TestKit.expectMsgType(TestKit.scala:718)
[info]   at org.apache.gearpump.streaming.examples.complexdag.DagSpec$$anonfun$3.apply$mcV$sp(DagSpec.scala:52)
[info]   at org.apache.gearpump.streaming.examples.complexdag.DagSpec$$anonfun$3.apply(DagSpec.scala:42)
[info]   at org.apache.gearpump.streaming.examples.complexdag.DagSpec$$anonfun$3.apply(DagSpec.scala:42)
[info]   at org.scalatest.Transformer$$anonfun$apply$1.apply$mcV$sp(Transformer.scala:22)
[info]   at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
[info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
```

**Comment by clockfly** [comment]
+1 for issue 959.
+0 for issue 960

For issue 960, as it is a costy operation to create a test cluster, changing the testcluster implementation may more easy trigger the UT failure.

**Comment by clockfly** [comment]
#959 is merged.

**Comment by kkasravi** [comment]
This is incorrect. Test time difference between creating a TestCluster per test suite and just one for all suites under services is negligible. See below timings

Time to run when creating a cluster per test suite under services
```
[info] Run completed in 3 seconds, 623 milliseconds.
[info] Total number of tests run: 13
[info] Suites: completed 10, aborted 0
[info] Tests: succeeded 13, failed 0, canceled 0, ignored 0, pending 0
[info] All tests passed.
```

Time to run when creating just one TestCluster for all test suites under services
```
[info] Run completed in 3 seconds, 208 milliseconds.
[info] Total number of tests run: 13
[info] Suites: completed 10, aborted 0
[info] Tests: succeeded 13, failed 0, canceled 0, ignored 0, pending 0
```
Also since the ClockService is never shut down after services test runs, 
it may cause various other problems in other test suites.

There are many problems with tests for SequenceFileIOSpec, DagSpec, SOLSpec and TransportSpec 1

1. they start a masterHarness per test rather than a testsuite - potentially much more costly than creating a TestCluster per suite since it appears that each test spawns a separate process. 
2. they spawn a separate process to run 
3. they accrue many disassociated messages and other errors due their tests - see below
4. they require way too much time to just submit an application. Time to run one test under gearpump-examples-sol is 12 seconds. There should be a separate story to resolve some of these problems.

[WARN] [05/27/2015 22:38:34.106] [ReliableDeliverySupervisor] Association with remote system [akka.tcp://client1205992021@127.0.0.1:59328] has failed, address is now gated for [5000] ms. Reason is: [Disassociated].
[INFO] [05/27/2015 22:38:34.106] [LocalActorRef] Message [akka.remote.transport.ActorTransportAdapter$DisassociateUnderlying] from Actor[akka://master/deadLetters] to Actor[akka://master/system/transports/akkaprotocolmanager.tcp1/akkaProtocol-tcp%3A%2F%2Fmaster%40127.0.0.1%3A59329-4#1356873985] was not delivered. [4] dead letters encountered. This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.
[INFO] [05/27/2015 22:38:34.252] [redirect] [INFO] [05/27/2015 22:38:34.251] [ClusterConfig$] loading config file application.conf...
[INFO] [05/27/2015 22:38:34.654] [redirect] [INFO] [05/27/2015 22:38:34.654] [Slf4jLogger] Slf4jLogger started
[INFO] [05/27/2015 22:38:34.742] [redirect] [INFO] [05/27/2015 22:38:34.741] [Remoting] Starting remoting
[INFO] [05/27/2015 22:38:34.905] [redirect] [INFO] [05/27/2015 22:38:34.905] [Remoting] Remoting started; listening on addresses :[akka.tcp://client1993150949@127.0.0.1:59331]
[INFO] [05/27/2015 22:38:34.934] [redirect] [INFO] [05/27/2015 22:38:34.934] [Metrics$] Metrics is enabled...,  false
[INFO] [05/27/2015 22:38:34.936] [redirect] [INFO] [05/27/2015 22:38:34.936] [ClientContext] Starting system client1993150949
[INFO] [05/27/2015 22:38:34.944] [redirect] [INFO] [05/27/2015 22:38:34.944] [ClientContext] Creating master proxy Actor[akka://client1993150949/user/client1993150949#1034391742] for master list: List(HostPort(127.0.0.1,59319))
[INFO] [05/27/2015 22:38:34.946] [redirect] [INFO] [05/27/2015 22:38:34.946] [MasterProxy@client1993150949] Contacts point URL: akka.tcp://master@127.0.0.1:59319/user/master
[INFO] [05/27/2015 22:38:34.949] [redirect] [INFO] [05/27/2015 22:38:34.949] [MasterProxy@client1993150949] sending identity to ActorSelection[Anchor(akka.tcp://master@127.0.0.1:59319/), Path(/user/master)]
[INFO] [05/27/2015 22:38:34.950] [redirect] [INFO] [05/27/2015 22:38:34.950] [MasterProxy@client1993150949] Master Proxy is started...
[INFO] [05/27/2015 22:38:34.971] [redirect] [INFO] [05/27/2015 22:38:34.971] [ClusterConfig$] loading config file applic

**Comment by clockfly** [comment]
OK

+1

**Pull request merged**
