### PR TITLE
fix #359, Allow travis to auto publish signed artifacts to nexus sonatyp...

### LINKED ISSUE #359: Allow travis to auto publish signed artifacts to nexus sonatype for snapshot and release builds
This is outlined in the article http://blog.eigengo.com/2014/05/25/sbt-and-oss-nexus/#more-5583 and requires the sbt-release plugin.

### PR DESCRIPTION
**Pull request by clockfly**
...e for snapshot and release builds

[Review on Reviewable](https://reviewable.io/reviews/intel-hadoop/gearpump/374)

### CODE REVIEW

**Comment by clockfly** [comment]
It works

```
[0m[[0minfo[0m] [0m	published gearpump-examples_2.11 to https://oss.sonatype.org/service/local/staging/deploy/maven2/com/github/intel-hadoop/gearpump-examples_2.11/0.2.3/gearpump-examples_2.11-0.2.3-sources.jar[0m
[0m[[0minfo[0m] [0m	published gearpump-examples_2.11 to https://oss.sonatype.org/service/local/staging/deploy/maven2/com/github/intel-hadoop/gearpump-examples_2.11/0.2.3/gearpump-examples_2.11-0.2.3-javadoc.jar.asc[0m
[0m[[0minfo[0m] [0m	published gearpump-examples_2.11 to https://oss.sonatype.org/service/local/staging/deploy/maven2/com/github/intel-hadoop/gearpump-examples_2.11/0.2.3/gearpump-examples_2.11-0.2.3.pom.asc[0m
[0m[[0minfo[0m] [0m	published gearpump-examples_2.11 to https://oss.sonatype.org/service/local/staging/deploy/maven2/com/github/intel-hadoop/gearpump-examples_2.11/0.2.3/gearpump-examples_2.11-0.2.3.jar.asc[0m
[0m[[0minfo[0m] [0m	published gearpump-examples_2.11 to https://oss.sonatype.org/service/local/staging/deploy/maven2/com/github/intel-hadoop/gearpump-examples_2.11/0.2.3/gearpump-examples_2.11-0.2.3-sources.jar.asc[0m
[0m[[0minfo[0m] [0m	published gearpump-examples_2.11 to https://oss.sonatype.org/service/local/staging/deploy/maven2/com/github/intel-hadoop/gearpump-examples_2.11/0.2.3/gearpump-examples_2.11-0.2.3.jar[0m
[0m[[0minfo[0m] [0m	published gearpump-examples_2.11 to https://oss.sonatype.org/service/local/staging/deploy/maven2/com/github/intel-hadoop/gearpump-examples_2.11/0.2.3/gearpump-examples_2.11-0.2.3-javadoc.jar[0m
[0m[[0minfo[0m] [0m	published gearpump-examples_2.11 to https://oss.sonatype.org/service/local/staging/deploy/maven2/com/github/intel-hadoop/gearpump-examples_2.11/0.2.3/gearpump-examples_2.11-0.2.3.pom[0m
[0m[[0minfo[0m] [0m	published gearpump-examples-kafka_2.11 to https://oss.sonatype.org/service/local/staging/deploy/maven2/com/github/intel-hadoop/gearpump-examples-kafka_2.11/0.2.3/gearpump-examples-kafka_2.11-0.2.3.pom[0m
[0m[[0minfo[0m] [0m	published gearpump-examples-kafka_2.11 to https://oss.sonatype.org/service/local/staging/deploy/maven2/com/github/intel-hadoop/gearpump-examples-kafka_2.11/0.2.3/gearpump-examples-kafka_2.11-0.2.3-javadoc.jar.asc[0m
[0m[[0minfo[0m] [0m	published gearpump-examples-kafka_2.11 to https://oss.sonatype.org/service/local/staging/deploy/maven2/com/github/intel-hadoop/gearpump-examples-kafka_2.11/0.2.3/gearpump-examples-kafka_2.11-0.2.3-sources.jar.asc[0m
[0m[[0minfo[0m] [0m	published gearpump-examples-kafka_2.11 to https://oss.sonatype.org/service/local/staging/deploy/maven2/com/github/intel-hadoop/gearpump-examples-kafka_2.11/0.2.3/gearpump-examples-kafka_2.11-0.2.3-sources.jar[0m
[0m[[0minfo[0m] [0m	published gearpump-examples-kafka_2.11 to https://oss.sonatype.org/service/local/staging/deploy/maven2/com/github/intel-hadoop/gearpump-examples-kafka_2.11/0.2.3/gearpump-examples-kafka_2.11-0.2.3.pom.asc[0m
[0m[[0minfo[0m] [0m	published gearpump-examples-kafka_2.11 to https://oss.sonatype.org/service/local/staging/deploy/maven2/com/github/intel-hadoop/gearpump-examples-kafka_2.11/0.2.3/gearpump-examples-kafka_2.11-0.2.3.jar.asc[0m
[0m[[0minfo[0m] [0m	published gearpump-examples-kafka_2.11 to https://oss.sonatype.org/service/local/staging/deploy/maven2/com/github/intel-hadoop/gearpump-examples-kafka_2.11/0.2.3/gearpump-examples-kafka_2.11-0.2.3.jar[0m
[0m[[0minfo[0m] [0m	published gearpump-examples-kafka_2.11 to https://oss.sonatype.org/service/local/staging/deploy/maven2/com/github/intel-hadoop/gearpump-examples-kafka_2.11/0.2.3/gearpump-examples-kafka_2.11-0.2.3-javadoc.jar[0m
[0m[[32msuccess[0m] [0mTotal time: 120 s, completed Jan 27, 2015 3:58:18 PM[0m
[0m[[0minfo[0m] [0mNexus repository URL: https://oss.sonatype.org/service/local[0m
[0m[[0minfo[0m] [0mNexus repository URL: https://oss.sonatype.org/service/local[0m
[0m[[0minfo[0m] [0mNexus repository URL: https://oss.sonatype.org/service/local[0m
[0m[[0minfo[0m] [0mNexus repository URL: https://oss.sonatype.org/service/local[0m
[0m[[0minfo[0m] [0mNexus repository URL: https://oss.sonatype.org/service/local[0m
[0m[[0minfo[0m] [0mNexus repository URL: https://oss.sonatype.org/service/local[0m
[0m[[0minfo[0m] [0mNexus repository URL: https://oss.sonatype.org/service/local[0m
[0m[[0minfo[0m] [0mNexus repository URL: https://oss.sonatype.org/service/local[0m
[0m[[0minfo[0m] [0mNexus repository URL: https://oss.sonatype.org/service/local[0m
[0m[[0minfo[0m] [0mNexus repository URL: https://oss.sonatype.org/service/local[0m
[0m[[0minfo[0m] [0mReading staging repository profiles...[0m
[0m[[0minfo[0m] [0mReading staging repository profiles...[0m
[0m[[0minfo[0m] [0mReading staging repository profiles...[0m
[0m[[0minfo[0m] [0mReading staging repository profiles...[0m
[0m[[0minfo[0m] [0mNexus repository URL: https://oss.sonatype.org/service/local[0m
[0m[[0minfo[0m] [0mReading staging repository profiles...[0m
[0m[[0minfo[0m] [0mNexus repository URL: https://oss.sonatype.org/service/local[0m
[0m[[0minfo[0m] [0mReading staging repository profiles...[0m
[0m[[0minfo[0m] [0mReading staging repository profiles...[0m
[0m[[0minfo[0m] [0mReading staging repository profiles...[0m
[0m[[0minfo[0m] [0mReading staging repository profiles...[0m
[0m[[0minfo[0m] [0mReading staging repository profiles...[0m
[0m[[0minfo[0m] [0mReading staging repository profiles...[0m
[0m[[0minfo[0m] [0mReading staging repository profiles...[0m
[0m[[0minfo[0m] [0mReading staging profiles...[0m
[0m[[0minfo[0m] [0mReading staging profiles...[0m
[0m[[0minfo[0m] [0mReading staging profiles...[0m
[0m[[0minfo[0m] [0mReading staging profiles...[0m
[0m[[0minfo[0m] [0mReading staging profiles...[0m
[0m[[0minfo[0m] [0mReading staging profiles...[0m
[0m[[0minfo[0m] [0mReading staging profiles...[0m
[0m[[0minfo[0m] [0mReading staging profiles...[0m
[0m[[0minfo[0m] [0mReading staging profiles...[0m
[0m[[0minfo[0m] [0mReading staging profiles...[0m
[0m[[0minfo[0m] [0mReading staging profiles...[0m
[0m[[0minfo[0m] [0mReading staging profiles...[0m
[0m[[0minfo[0m] [0mClosing staging repository [comgithubintel-hadoop-1004] status:open, profile:com.github.intel-hadoop(885ce7e1beab93)[0m
[0m[[0minfo[0m] [0mClosing staging repository [comgithubintel-hadoop-1004] status:open, profile:com.github.intel-hadoop(885ce7e1beab93)[0m
[0m[[0minfo[0m] [0mChecking activity logs of comgithubintel-hadoop-1004 ...[0m
[0m[[0minfo[0m] [0mClosing staging repository [comgithubintel-hadoop-1004] status:open, profile:com.github.intel-hadoop(885ce7e1beab93)[0m
[0m[[0minfo[0m] [0mClosing staging repository [comgithubintel-hadoop-1004] status:open, profile:com.github.intel-hadoop(885ce7e1beab93)[0m
[0m[[0minfo[0m] [0mClosing staging repository [comgithubintel-hadoop-1004] status:open, profile:com.github.intel-hadoop(885ce7e1beab93)[0m
[0m[[0minfo[0m] [0mClosing staging repository [comgithubintel-hadoop-1004] status:open, profile:com.github.intel-hadoop(885ce7e1beab93)[0m
[0m[[0minfo[0m] [0mClosing staging repository [comgithubintel-hadoop-1004] status:open, profile:com.github.intel-hadoop(885ce7e1beab93)[0m
[0m[[0minfo[0m] [0mClosing staging repository [comgithubintel-hadoop-1004] status:open, profile:com.github.intel-hadoop(885ce7e1beab93)[0m
[0m[[0minfo[0m] [0mClosing staging repository [comgithubintel-hadoop-1004] status:open, profile:com.github.intel-hadoop(885ce7e1beab93)[0m
[0m[[0minfo[0m] [0mClosing staging repository [comgithubintel-hadoop-1004] status:open, profile:com.github.intel-hadoop(885ce7e1beab93)[0m
[0m[[0minfo[0m] [0mClosing staging repository [comgithubintel-hadoop-1004] status:open, profile:com.github.intel-hadoop(885ce7e1beab93)[0m
[0m[[0minfo[0m] [0mClosing staging repository [comgithubintel-hadoop-1004] status:open, profile:com.github.intel-hadoop(885ce7e1beab93)[0m
[0m[[0minfo[0m] [0mChecking activity logs of comgithubintel-hadoop-1004 ...[0m
[0m[[0minfo[0m] [0mClose process is in progress ...[0m
[0m[[0minfo[0m] [0mChecking activity logs of comgithubintel-hadoop-1004 ...[0m
[0m[[0minfo[0m] [0mClose process is in progress ...[0m
[0m[[0minfo[0m] [0mChecking activity logs of comgithubintel-hadoop-1004 ...[0m
[0m[[0minfo[0m] [0mClosed successfully[0m
[0m[[0minfo[0m] [0mPromoting staging repository [comgithubintel-hadoop-1004] status:closed, profile:com.github.intel-hadoop(885ce7e1beab93)[0m
[0m[[0minfo[0m] [0mChecking activity logs of comgithubintel-hadoop-1004 ...[0m
[0m[[0minfo[0m] [0mChecking activity logs of comgithubintel-hadoop-1004 ...[0m
[0m[[0minfo[0m] [0mRelease process is in progress ...[0m
[0m[[0minfo[0m] [0mChecking activity logs of comgithubintel-hadoop-1004 ...[0m
[0m[[0minfo[0m] [0mRelease process is in progress ...[0m
[0m[[0minfo[0m] [0mChecking activity logs of comgithubintel-hadoop-1004 ...[0m
[0m[[0minfo[0m] [0mPromoted successfully[0m
[0m[[0minfo[0m] [0mDropping staging repository [comgithubintel-hadoop-1004] status:released, profile:com.github.intel-hadoop(885ce7e1beab93)[0m
[0m[[0minfo[0m] [0mDropped successfully: comgithubintel-hadoop-1004[0m
```

**Comment by kkasravi** [comment]
PR build fails above with:
[0m[[0minfo[0m] [0m[31m*** 1 TEST FAILED ***[0m[0m
[0m[[31merror[0m] [0mFailed: Total 7, Failed 1, Errors 0, Passed 6[0m
[0m[[31merror[0m] [0mFailed tests:[0m
[0m[[31merror[0m] [0m	org.apache.gearpump.experiments.cluster.appmaster.ExecutorLauncherSpec[0m

I looked at the latest 'build/passing' log (https://s3.amazonaws.com/archive.travis-ci.org/jobs/48503416/log.txt or https://travis-ci.org/intel-hadoop/gearpump/builds/48503415) and didn't see any 'published' messages...

**Comment by clockfly** [comment]
@kkasravi 

Since the publishToSonatype process is only triggered when creating a tag. It will not show up in build log of this PR. In github, we are not allowed to create tag in PR.

The test was made by creating a 0.2.3 tag, and then publish to sonatype.
You can check:
https://travis-ci.org/intel-hadoop/gearpump/builds/48489177
 instead, or
https://s3.amazonaws.com/archive.travis-ci.org/jobs/48489178/log.txt

After publishing, it shows in sonatype
https://oss.sonatype.org/service/local/repositories/releases/content/com/github/intel-hadoop/

**Comment by clockfly** [comment]
I created a document about how to create a release and trigger a release publishing.
check here: https://github.com/intel-hadoop/gearpump/blob/master/doc/ReleaseProcess.md

**Comment by kkasravi** [comment]
+1, but should we also publish SNAPSHOT's? I think this would be valuable in maven, especially if we're collaborating with external individuals or soliciting feedback on certain features.

**Comment by clockfly** [comment]
yes, we are also publishing SNAPSHOT.

The SNAPSHOT build will be triggered when:
1. It is on Master branch
2. It is at the time of PR merge, not PR submit.

check  the code here:
```
if [[ $TRAVIS_BRANCH == "master" && $TRAVIS_PULL_REQUEST == "false" && $TRAVIS_TAG
+  == "" ]] then sbt publish; fi
```


We should be able to trigger the snapshot build when we merge this PR to master.

**Comment by clockfly** [comment]
Check the snapshot build in progress at 
https://travis-ci.org/intel-hadoop/gearpump/builds/48580276

check the tag build in progress at
https://travis-ci.org/intel-hadoop/gearpump/builds/48580446

**Pull request merged**
