### PR TITLE
Fixes #27 Integrate GearPump Scheduler into YARN

### PR DESCRIPTION
**Pull request by kkasravi**
YarnAM is now running successfully. Master and workers are not yet launching correctly. 

[Review on Reviewable](https://reviewable.io/reviews/intel-hadoop/gearpump/583)

### CODE REVIEW

**Comment by huafengw** [comment]
Hi Kam, seems now the AppMasterSpec often fails, may be you could increase the timeout duration of line 122.

**Comment by kkasravi** [comment]
Thanks Huafeng - I'll get to it later tonight or tomorrow morning

**Comment by clockfly** [comment]
+1

**Comment by kkasravi** [comment]
Thanks Sean :)

**Pull request merged**
