### PR TITLE
Fixes #27 Integrate Gear scheduler with YARN

### PR DESCRIPTION
**Pull request by kkasravi**
rebase master into yarn

[Review on Reviewable](https://reviewable.io/reviews/intel-hadoop/gearpump/539)

### CODE REVIEW

**Comment by clockfly** [comment]
-1

Seems unrelated with yarn.

**Comment by kkasravi** [comment]
This was a sync with master that disabled kafka due to build breakage.

**Comment by huafengw** [comment]
Hi Kam, can you sync branch yarn with master to check whether the problem still exist?

**Comment by kkasravi** [comment]
Yes, I will sync yarn with master and resubmit a new PR. Thanks.

**Comment by kkasravi** [comment]
Hi Huafeng - Seems to still exist in build 831 on travis. See my comments here
https://github.com/intel-hadoop/gearpump/pull/554

**Comment by huafengw** [comment]
Hi Kam, I tried to rebuild the branch yarn to see whether the failure is random but you deleted your own branch, could you restore it?

**Comment by huafengw** [comment]
I think the failure is random because the build 832 on travis succeed, which is also on branch yarn.

**Comment by kkasravi** [comment]
Yes, it's random since we did not change the failing tests.

**Pull request closed without merging**
