### PR TITLE
[TaskActor] task onStart should be called after the network transport la...

### PR DESCRIPTION
**Pull request by clockfly**
...yer is ready

### CODE REVIEW

**Comment by manuzhang** [comment]
UT failed.

```
[info] MinMaxMetricsStore
[info] - should retain min and max metrics data and expire old value *** FAILED ***
[info]   "[C]" did not equal "[B]" (HistoryMetricsServiceSpec.scala:106)
```

```
[info] FileServerSpec:
[info] The file server
[info] - should server the data previously stored *** FAILED ***
[info]   akka.pattern.AskTimeoutException: Ask timed out on [Actor[akka://FileServerSpec/user/$a#-735078156]] after [10000 ms]
[info]   at akka.pattern.PromiseActorRef$$anonfun$1.apply$mcV$sp(AskSupport.scala:333)
[info]   at akka.actor.Scheduler$$anon$7.run(Scheduler.scala:117)
[info]   at scala.concurrent.Future$InternalCallbackExecutor$.unbatchedExecute(Future.scala:599)
[info]   at scala.concurrent.BatchingExecutor$class.execute(BatchingExecutor.scala:109)
[info]   at scala.concurrent.Future$InternalCallbackExecutor$.execute(Future.scala:597)
[info]   at akka.actor.LightArrayRevolverScheduler$TaskHolder.executeTask(Scheduler.scala:467)
[info]   at akka.actor.LightArrayRevolverScheduler$$anon$8.executeBucket$1(Scheduler.scala:419)
[info]   at akka.actor.LightArrayRevolverScheduler$$anon$8.nextTick(Scheduler.scala:423)
[info]   at akka.actor.LightArrayRevolverScheduler$$anon$8.run(Scheduler.scala:375)
[info]   at java.lang.Thread.run(Thread.java:745)
[info]   ...
```

**Comment by huafengw** [comment]
I think there is still a potential bug. For example, in example stockcrawler, the QueryServer will ask AppMaster for AppMasterDetail in onStart(), and AppMaster will ask TaskManager for TaskList, but at this moment, chances are that the TaskManager is still in StartApplication state because not all tasks has registered.

**Comment by clockfly** [comment]
@huafengw 
What is your suggestion?

**Comment by clockfly** [comment]
@manuzhang 

The UT fail is irrelevant.

**Comment by clockfly** [comment]
UT pass

**Comment by huafengw** [comment]
+1

**Pull request merged**
