### PR TITLE
fix #1210, fix kafka examples

### LINKED ISSUE #1210: examples/streaming/kafka fails to run when submitted in UI
[Story](https://www.pivotaltracker.com/story/show/99844130)
log info will be provided

### PR DESCRIPTION
**Pull request by manuzhang**
[Review on Reviewable](https://reviewable.io/reviews/intel-hadoop/gearpump/1219)

### CODE REVIEW

**Comment by manuzhang** [comment]
```scala
   List("org.scala-lang.modules" %% "scala-parser-combinators" % "1.0.4")
```
The change is because the scala-parser-combinators library required by kafka but excluded in assembly is separated from scala core in 2.11.

**Comment by clockfly** [comment]
Can we avoid puting this dependency in core list?

**Comment by manuzhang** [comment]
here is a list of scala libraries that are excluded from assembly (sbt-assembly)

```
      "scala-actors",
      "scala-compiler",
      "scala-continuations",
      "scala-library",
      "scala-parser-combinators",
      "scala-reflect",
      "scala-swing",
      "scala-xml"
```

If not provided in core lib, they won't be on classpath and applications fail to run.
If we include them into assembled jar, they may be conflicting with scala libraries already in core lib and cause unpredictable results.

**Comment by clockfly** [comment]
+1

**Pull request merged**
