### PR TITLE
add an example about writing Parquet format file

### PR DESCRIPTION
**Pull request by huafengw**
This pull request demonstrates how to write messages into a Parquet format file.

How to run this example:
1. sbt avro:generate
2. sbt assembly
3. bin/gear app -jar jarfile -output file:///tmp/parquet

### CODE REVIEW

**Comment by kkasravi** [comment]
+1

**Comment by kkasravi** [comment]
This test fails which is unrelated

[info] SubmitApplicationRequestServiceSpec
[info] - should return an AppMasterDataDetail dag that matches SubmitApplicationRequest dag *** FAILED ***
[info]   Request was neither completed nor rejected within 1 second (SubmitApplicationRequestServiceSpec.scala:168)

**Comment by kkasravi** [comment]
@huafengw Could you add experiments/parquet/README.md with above notes on how to run?

**Comment by huafengw** [comment]
@kkasravi README.md is added

**Comment by huafengw** [comment]
Will submit a new pr based on Kam's work

**Pull request closed without merging**
