### PR TITLE
fix #928 improve the allowSendingMsg performance

### LINKED ISSUE #928: costly allowSendingMoreMessages() hurt performance
Every time TaskActor handles a message, it will call function allowSendingMoreMessages(), which is observed to be a costly function.

### PR DESCRIPTION
**Pull request by huafengw**

### CODE REVIEW

**Comment by huafengw** [comment]
After applying this patch, I did a simple performance test.

For gearpump sol benchmark, I run 48 producers and 48 processors on 16 workers.

Version | Throughput | Latency
------------ | ------------- | ---------------
Without patch | 11,000,000 msg/s | 5ms
With the patch | 14,000,000 msg/s | 8ms

Also, this will improvement the performance of storm-over-gearpump.

**Comment by kkasravi** [comment]
@huafengw great job!

**Comment by huafengw** [comment]
Update the pr according to Sean's advice.

**Comment by clockfly** [comment]
+1

**Pull request merged**
