### PR TITLE
fix #1178: can query application log again

### LINKED ISSUE #1178: Read application's config file timeout
For instance `http://127.0.0.1:8090/api/v1.0/appmaster/1/config`

### PR DESCRIPTION
**Pull request by stanleyxu2005**
[Review on Reviewable](https://reviewable.io/reviews/intel-hadoop/gearpump/1181)

### CODE REVIEW

**Comment by clockfly** [comment]
UT AppMasterServiceSpec failed.

**Comment by manuzhang** [comment]
PR #1179 contains this

**Comment by stanleyxu2005** [comment]
@clockfly UT has been fixed

**Comment by clockfly** [comment]
+1

**Pull request merged**
