### PR TITLE
Fixes #269

### LINKED ISSUE #269: Define UI Dashboard structure
Sub task of master #11 
Provide the dashboard framework which should support an extensible set of widgets that can be added to the dashboard. The dashboard should also support tabs - where each tab will expose the widgets relevant to that tab. The dashboard framework should allow realtime data to be streamed within a given widget. Angular is a good candidate for the framework. D3 is a good candidate for charts. The framework should be served by spray. Best practices should be followed for frontend components. In this case we should use npm, bower, grunt.

### PR DESCRIPTION
**Pull request by kkasravi**
Note this is a very early checkin that does not build under sbt (yet). 
It defines a frontend stack that uses angularjs, nvd3 and is based on 
the angular-dashboard-framework. Included is a screenshot that shows a basic 
dashboard which can be edited to 
- add new (registered) widgets 
- rearrange widget locations 
- resize widgets
- save configuration 

This early version can be built and run by doing
- npm install
- bower install
- grunt server
- open http://localhost:9001

This assumes you've installed npm, bower and grunt. This will eventually be done by sbt.
The widgets needed for gearpump will be added in subsequent issues referenced by the master #11.
The REST API will also be added and referenced by master #11. This REST API will likely include websockets so that events can be pushed to the UI by the master. This will be modeled after the SparkUI which enables an event bus that listeners can subscribe to. Master #11 will include a design document in the near future.

screen shot 2015-01-10 at 12 01 11 am

[Review on Reviewable](https://reviewable.io/reviews/intel-hadoop/gearpump/284)

### CODE REVIEW

**Comment by clockfly** [comment]
@kkasravi 

Please use this PR to track the experiments we made.

**Comment by kkasravi** [comment]
Hi Sean

PR in comment above was not a link...

**Comment by clockfly** [comment]
Please rebase this on ui branch

**Comment by kkasravi** [comment]
Please merge into ui_portal. I will be adding the DAG widget afterwards.

**Pull request closed without merging**
